#!/usr/bin/env python3
"""Build visits/index.json by scanning the visits/ directory for *.md files.
Also extract frontmatter for quick metadata access."""
import os, json, re

base = os.path.dirname(__file__)
visits_dir = os.path.join(base, 'visits')

results = []
for fname in sorted(os.listdir(visits_dir)):
    if not fname.endswith('.md'):
        continue
    if fname == 'README.md':
        continue
    item_id = fname[:-3]  # strip .md
    if not (item_id.startswith('spot-') or item_id.startswith('fest-')):
        continue
    path = os.path.join(visits_dir, fname)
    with open(path, encoding='utf-8') as f:
        content = f.read()
    # Frontmatter
    fm = {}
    m = re.match(r'^---\n(.*?)\n---\n', content, re.DOTALL)
    if m:
        for line in m.group(1).split('\n'):
            line = line.strip()
            if ':' in line:
                k, v = line.split(':', 1)
                fm[k.strip()] = v.strip()
    # Title (first H1)
    title_match = re.search(r'^# (.+)$', content, re.MULTILINE)
    title = title_match.group(1).strip() if title_match else item_id
    # Body without frontmatter
    body = re.sub(r'^---\n.*?\n---\n', '', content, count=1, flags=re.DOTALL)
    results.append({
        'id': item_id,
        'title': title,
        'visited_date': fm.get('visited_date'),
        'rating': fm.get('rating'),
        'companions': fm.get('companions'),
        'weather': fm.get('weather'),
        'duration': fm.get('duration'),
        'body': body.strip(),
    })

out = {
    '_comment': 'Auto-generated by build_visits.py. Do not edit by hand.',
    'visits': results,
}
with open(os.path.join(visits_dir, 'index.json'), 'w', encoding='utf-8') as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print(f'Indexed {len(results)} visit entries')
for v in results:
    print(f"  - {v['id']}: {v['title'][:40]}")
